/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface PurchaseRecord {
  'userId' : Principal,
  'materialId' : string,
  'purchasedAt' : Time,
  'stripeSessionId' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface StudyMaterial {
  'id' : string,
  'title' : string,
  'contentType' : string,
  'isPremium' : boolean,
  'createdAt' : Time,
  'tags' : Array<string>,
  'description' : string,
  'subjectId' : string,
  'blobId' : ExternalBlob,
  'uploader' : Principal,
  'downloadCount' : bigint,
}
export interface StudyMaterialPublic {
  'id' : string,
  'title' : string,
  'contentType' : string,
  'isPremium' : boolean,
  'createdAt' : Time,
  'tags' : Array<string>,
  'description' : string,
  'subjectId' : string,
  'blobId' : [] | [ExternalBlob],
  'uploader' : Principal,
  'downloadCount' : bigint,
}
export interface Subject {
  'id' : string,
  'name' : string,
  'description' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSubject' : ActorMethod<[Subject], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimAdminIfFirst' : ActorMethod<[], boolean>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteMaterial' : ActorMethod<[string], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMaterial' : ActorMethod<[string], [] | [StudyMaterialPublic]>,
  'getMaterialBlobId' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getMaterialsBySubject' : ActorMethod<[string], Array<StudyMaterialPublic>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'getUserPurchases' : ActorMethod<[], Array<PurchaseRecord>>,
  'hasPurchased' : ActorMethod<[string], boolean>,
  'incrementDownloadCount' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listMaterials' : ActorMethod<[boolean], Array<StudyMaterialPublic>>,
  'recordPurchase' : ActorMethod<[PurchaseRecord], undefined>,
  'searchMaterials' : ActorMethod<[string], Array<StudyMaterialPublic>>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'uploadMaterial' : ActorMethod<[StudyMaterial], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];